[package]
name = "shadercloud/roactradial"
description = "This is a Roblox roact component that creates a radial menu. \n\nAs you probably know Roblox doesn't easily allow for circles or other shapes in their GUI, so this radial menu is created by using a combination of CanvasGroup, UICorners, Triangle images within ImageLabels to create the appearance of a circle.  \n\nCurrently the radial menu accepts a table of option elements which can include a Label, Icon and Color."
license = "MIT"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "selene.toml", "aftman.toml", ".gitignore", "TestPlace.project.json", "TestPlace.rbxl", "README.md",
]

[dependencies]
roact = "roblox/roact@1.4.4"